export enum Occupation {
    STUDENT = "STUDENT",
    PROFESSOR = "PROFESSOR",
    PRESIDENT = "PRESIDENT",
    MANAGER = "MANAGER",
    FACULTY_DEAN = "FACULTY_DEAN",
    FACULTY_ASSISTANT_DEAN = "FACULTY_ASSISTANT_DEAN",
    DEAN = "DEAN",
    ASSISTANT_DEAN = "ASSISTANT_DEAN",
    ADMIN = "ADMIN"
}
